### ISSUE TITLE
Cross platform support (Linux, OSX)

### ISSUE THREAD

**Issue by JuliusSweetland** [JuliusSweetland/OptiKey#105]
This would require the WPF components and Windows specific code (e.g. Win32 API calls) to be refactored - a large effort.

Closing issues #78 and #77 into this new issue.

**Comment by lucavice** [comment]
Optikey seems closely tied to .Net, WPF and Rx, as well as all the Win32 magic to get the always-on-top split-screen behaviour. I guess that a port to linux/osx would be an almost complete rewrite.

**Comment by JuliusSweetland** [comment]
@lucavice That is correct. There are projects like this http://grokys.github.io/perspex/perspex-alpha2/ but they won't cover even half of the funky stuff that's going on with Win32 calls etc.

**Comment by Gadal** [comment]
I wonder if we could use Wine.  If so, I think we'd also get OS X, FreeBSD, and Solaris for free.

**Comment by JuliusSweetland** [comment]
@Luca you're right. OptiKey is very tightly bound to Windows. Makes the
talk much harder, but obviously not impossible.

**Comment by JuliusSweetland** [comment]
Adding to big list of potential tasks and closing for now https://github.com/JuliusSweetland/OptiKey/issues/57

**Comment by alexandre-mbm** [comment]
I am enjoying OptiKey on Windows 10. Why sometimes there is not the split-screen behaviour? Bug or auto configuration?

**Comment by JuliusSweetland** [comment]
@alexandre-mbm If you are referring to when OptiKey takes up part of your screen, this is when OptiKey is docked to an edge. If you use the "Size & position" keyboard to move OptiKey to a screen edge, then move it OVER that edge OptiKey will dock and arrange other windows around it. If you then move OptiKey away from the docked edge it will break off the edge and float over other windows. Both modes have their advantages and disadvantages, so I supply the ability to switch between them.

**Comment by rdewolff** [comment]
Would be great to have this working on Mac OS X!

**Comment by JuliusSweetland** [comment]
I'm afraid this is currently unlikely.
