### ISSUE TITLE
Diy eyetracker

### ISSUE THREAD

**Issue by Joostvt** [JuliusSweetland/OptiKey#109]
Maybe a weird idea, but is it not possible to build our own eyetracker to make it even cheaper?

**Comment by JuliusSweetland** [comment]
@Joostvt It's possible. I originally built one to work with the ITU Gazetracker software (by Martin Tall who is one of the founders of TheEyeTribe). The camera cost me about £500. I don't realistically think that it is currently possible to undercut the prices we are seeing from TheEyeTribe ($100) and Tobii (EyeX=$150).
