### ISSUE TITLE
TextBox caret not updating position when using arrows (physical keys)

### ISSUE THREAD

**Issue by danielmoncada** [JuliusSweetland/OptiKey#110]
The caret in the text field does not move if physical "arrow" keys are pressed. I.e., when typing in Notepad using OptiKey and pressing the "left arrow" under the "Physical Keys" section, the Notepad's caret movies left one position but does not update the OptiKey caret.

OS: Windows 10
Version: 2.0.9.0 (release)

**Comment by JuliusSweetland** [comment]
@danielmoncada This is not supported at the momnet, but I'll leave this issue here as an enhancement. There are a few assumptions in the code that the caret should remain at the end of the string. I need to do a little work to change this.

**Comment by JuliusSweetland** [comment]
Moving to big list of potential tasks and closing this task for now.

**Comment by alexandre-mbm** [comment]
My hint is enable/disable in config and with possibility for access in run time.
