### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by Yano93** [JuliusSweetland/OptiKey#129]
I can translate english,Norwegian, Japanese, give me some work to do! My email is ltachiailin@gmail.com

**Comment by JuliusSweetland** [comment]
Hi, please join us. The localisation task is being discussed here:https://github.com/JuliusSweetland/OptiKey/issues/73
The actual translation is being done on this site: transifex.com/optikey/ - register as a translator for the languages you can speak and it'll give you a list of strings to translate.
Thank you and welcome aboard!

**Comment by Yano93** [comment]
hi again, Where is the Norwegian group?

**Comment by JuliusSweetland** [comment]
There is no specific task ("issue") on GitHub for Norwegian. I might start splitting creating an issue per language as the work starts on each one. In the mean time you can register, request Norwegian, and start translating on this website: www.transifex.com/optikey/

All general localisation discussion is here: https://github.com/JuliusSweetland/OptiKey/issues/73

**Comment by Yano93** [comment]
okay,
thanks!!
