### ISSUE TITLE
Phrases

### ISSUE THREAD

**Issue by JuliusSweetland** [JuliusSweetland/OptiKey#13]
- Button to add current output buffer to dictionary. MainVM generates hash, or error if not appropriate, then passes to Question keyboard class for display.
- Workflow: user must clear the output buffer and write phrase before saving.

**Comment by alexandre-mbm** [comment]
You speak "phrases" but in the dictionaries (en-US and es at least) I see words only.

**Comment by JuliusSweetland** [comment]
@alexandre-mbm Phrases have been implements, but there are none in the default US English dictionary. If you write out a phrase (e.g. "my name is Julius") then select the 'Add To Dictionary' key, it will offer to add the whole phrase to the dictionary. It will then be suggested if you start typing e.g. "my n", or if you type "mnij", or if you swipe over "m", "n", "i", "j". You can try it out, but this issue is complete I believe.

**Comment by alexandre-mbm** [comment]
- [ ] Me look other way to show more long phrases

Today my full name (five words) appears very small in the autocomplete field, for example. Hint to think: floating zoom box when doing field selection.
