### ISSUE TITLE
Left Mouse Click

### ISSUE THREAD

**Issue by drcpcreed** [JuliusSweetland/OptiKey#130]
Hello, I'm currently testing out the latest version (2.1.0.0) and the left-click doesn't seem to be working for me in mouse mode. 

I've got an older version (1.3.5.0) working on a different laptop and it seems to be fine there.

Not sure if this is a common problem?

**Comment by JuliusSweetland** [comment]
Can you provide more details about when left click is and is not working? thanks.

**Comment by drcpcreed** [comment]
Yes, I’ve got the Chrome browser open and trying to select the username/password fields in Gmail to login. I’ve tried using both the magnifier + left click and a left click on its own, but neither place the cursor in the field (although the click sound is played). I’ve also just tried creating a new tab within the browser, but again I don’t think it’s registering the click.

The right click seems to work as expected.

**Comment by drcpcreed** [comment]
A few more details – it seems like the left click moves the cursor to the location where you want to make a selection, but then is not actually performing the click. For example, if I look at the minimise icon in the web browser (with left click enabled), it highlights that icon (i.e. like it’s in a hover state), but the minimise action doesn’t happen.

The same also happens with applications in the taskbar – they get highlighted (as if they’re being hovered over), but the application doesn’t start.

I’m also finding the same issue with a double click (e.g. when trying to open a shortcut on the desktop).

**Comment by JuliusSweetland** [comment]
I'll try this evening. Which OS are you using and are you using the mouse
keyboard in a collapsed state (where there are only 6 or so available
actions), or the expanded state (where there are about 20 actions)?

**Comment by drcpcreed** [comment]
Great, thanks. Using Windows 8.1 – with the mouse in collapsed mode.

**Comment by drcpcreed** [comment]
Just a quick update – I think I’ve resolved this – it seems that the Mouse Warp feature for the Tobii EyeX may have been interfering. I’ve disabled it and everything seems to be working fine now.

**Comment by JuliusSweetland** [comment]
Excellent - great catch. I suspect that other software will be hooking mouse events so running more than one at a time will cause unexpected behaviour. I'll keep this in mind should other people experience similar problems. Thanks for finding this. I'll close this issue now.
