### ISSUE TITLE
Confusing mental model for docking/window position

### ISSUE THREAD

**Issue by kirstymcnaught** [JuliusSweetland/OptiKey#134]
I've played about with OptiKey for a while, and I can't figure out how to switch between 'Docked' and 'Floating' mode, and how the user is supposed to understand the difference. In the code, there's a concept of 'Docked' window state, vs. 'Floating' window state. In my mental model, this is the difference between being snapped to somewhere specific, vs. floating at an arbitrary position. However, it's also used to determine whether you're allowed to expand/collapse the selection, for instance when you're in mouse control mode. It doesn't seem to make sense that you shouldn't be allowed to minimise the set of controls just because you're in 'floating' mode. In particular, if you're in floating mode then "Collapse dock" is greyed out, but there's no way to find out why. 

In terms of changing from docked to floating mode, maybe I'm just missing something. The only place I've found relevant controls is in Menu -> Size & Position. In here, I have successfully managed to put it into docked mode, and get it floating again, but I have no idea how I did it each time. It seems that the states "Docked" and "Floating" aren't explicitly observable or settable by the user, they are just a side-effect of the size & position settings. This makes it very hard to understand things where the functionality depends on docked-state (such as the "Collapse Dock" button being greyed out).

Not sure if this is a bug, UX feature request or just information request, but thought it worth reporting.

**Comment by JuliusSweetland** [comment]
@kirstymcnaught I think the biggest issue here is my lack of accurate documentation (either on the wiki or instructional videos). These will follow, I've just been extremely busy recently.

When you start OptiKey it is docked to the top edge by default. Go to the menu and then the "Size & Position" keyboard and use the "Move" arrows to move OptiKey away from the docked edge. It should break away from its docked state and start floating. In this mode you can move it around freely. Now move it towards any screen edge (either jumping to an edge, or manually moving a step at a time to an edge) - when you get there make one more move to take you over the screen edge and OptiKey will dock to the edge. Once docked you can "Jump" to be docked on any other screen edge.

OptiKey was originally floating only in version 1. I added docking in version 2 in response to user requests that it was difficult to work with other applications from OptiKey. Docking automatically arranges other windows so seemed to solve the problem, however, it doesn't have any impact on some situations, such as fullscreen applications (videos, games, etc), or the start interface in Windows 8/8.1. For this reason I thought the ability to float OptiKey and move it around was still useful.

Lastly, the expand/collapse concept is suppressed when floating it doesn't feel right to me to change the size and shape of the floating window, although this is entirely possible if you think it has value. I was just trying to keep things simple and consistent.

**Comment by JuliusSweetland** [comment]
Moving to BACKLOG

**Comment by kirstymcnaught** [comment]
I've been using OptiKey for months and I still get confused by this! I keep wanting 'jump' to dock it, so my usual workflow (if it's floating and I want to dock it) is:

- jump to edge. jump again. jump again. wonder why it isn't docking. expand as many times as I need to fill the edge. Jump again. Get desperate. Remember I need to move it again. 

I know there's an easier workflow (jump once, move once) but it isn't what comes to mind when I try to figure it out after not changing to for a while. 

I think it would be a lot easier to use if there were buttons on the Size/Position keyboard to explicitly switch between floating and docked. If the "Adjust by XX pixels" button was less wide, there would be space for two mode mutually exlusive buttons.
