### ISSUE TITLE
"Magnetic cursor" doesn't respect sleep mode.

### ISSUE THREAD

**Issue by kirstymcnaught** [JuliusSweetland/OptiKey#135]
Reported for OptiKey v2.1.0, Windows 8.1, using EyeTribe as input. 

Use case - wanting to close OptiKey with the mouse while using a very badly calibrated Eye Tracker.

- Launch OptiKey
- Go to "Mouse"
- Turn on "Magnetic Cursor"
- "Back"
- "Sleep"

OptiKey is now in sleep mode, but the cursor is still being controlled by the EyeGaze.

**Comment by JuliusSweetland** [comment]
Fixed with commit 71a3121c2fc7b51b71d94854ff978da000a2d9fb

**Comment by JuliusSweetland** [comment]
@kirstymcnaught The fix for this has just been released in v2.1.1

**Comment by kirstymcnaught** [comment]
@JuliusSweetland Thanks for the quick work!

**Comment by alexandre-mbm** [comment]
I do not understand what is the magnetic cursor and I can not find this information in the wiki.

**Comment by JuliusSweetland** [comment]
@alexandre-mbm It's a key on the mouse keyboard, which, when locked down (pressed), means the mouse cursor follows wherever the user directs their attention, e.g. if you are using an eye tracker and turn on magnetic mouse then the mouse cursor will follow wherever you look.

**Comment by alexandre-mbm** [comment]
What are the uses for this?

**Comment by JuliusSweetland** [comment]
@alexandre-mbm You can control the cursor, which can be used to interact with games, or other accessibility software which reacts to the mouse.
