### ISSUE TITLE
Exception while using Mouse 

### ISSUE THREAD

**Issue by Ar2rZ** [JuliusSweetland/OptiKey#146]
in class PontExtentions

return new Point(Convert.ToInt32(points.Average(p => p.X)), Convert.ToInt32(points.Average(p => p.Y)));
OverFlowException
details: {"Value was either too large or too small for an Int32."}

How to reproduce:

on Mouse menu ==> one click ==> try to look at the windows  task bar ==> not finished capture ,look at the somewhere at the main window, the look again on the task bar, repeat two three times, sometimes more- should get exception.

**Comment by Ar2rZ** [comment]
after some time plying with mouse functions is stop capturing(pie is not appearing any more ), although is still showing an arrow, but is doing nothing.. big arrow still following the look. and can be started new OptiKey, old one instance of OptiKey still showing on the screen.

**Comment by JuliusSweetland** [comment]
Do you have the full stack trace of the exception so I can see exactly where the call is coming from?

**Comment by Ar2rZ** [comment]
it will be simple fix - put into try and catch for getting x and y. 
but i don't know whether is proper fix, 
on my system is giving invalid values for mouse movement. in this method 
public IObservable<TriggerSignal> Sequence

var pointAndKeyValueSubscription = pointAndKeyValueSource
                            .Where(_ => disposed == false)
                            .Where(tp => tp.Value != null) //Filter out stale indicators - the fixation progress is not reset by the points sequence being stale
                            .Select(tp => new Timestamped<PointAndKeyValue>(tp.Value.Value, tp.Timestamp))
                            .Subscribe(point =>
                            {
                                //Maintain a buffer which contains points which fill the lockOnTime 
                                buffer.Add(new Timestamped<PointAndKeyValue>(point.Value, point.Timestamp));

on of the point.Value sometimes is given NaN,NaN

**Comment by Ar2rZ** [comment]
at System.Convert.ToInt32(Double value)
   at JuliusSweetland.OptiKey.Extensions.PointExtensions.CalculateCentrePoint(List`1 points) in F:\Development\GitHub\OptiKey\src\JuliusSweetland.OptiKey\Extensions\PointExtensions.cs:line 18

**Comment by JuliusSweetland** [comment]
I see. Ok thanks Arthur. I'll take a look soon.

**Comment by JuliusSweetland** [comment]
I think I'll just need to filter out NaN on the point observable. You're using TheEyeTribe in this scenario aren't you? I guess it outputs NaN for x and/or y sometimes, which isn't ideal. I'll put something together for you to test.

**Comment by Ar2rZ** [comment]
I am using Tobii Eyex,
i did not received EyeTribe yet.

**Comment by JuliusSweetland** [comment]
TobiiEyeXPointService line 57 change the add logic to:
```
            add
            {
                if (pointEvent == null)
                {
                    Log.Info("Checking the state of the Tobii service...");

                    switch (EyeXHost.EyeXAvailability)
                    {
                        case EyeXAvailability.NotAvailable:
                            PublishError(this, new ApplicationException(Resources.TOBII_EYEX_ENGINE_NOT_FOUND));
                            return;

                        case EyeXAvailability.NotRunning:
                            PublishError(this, new ApplicationException(Resources.TOBII_EYEX_ENGINE_NOT_RUNNING));
                            return;
                    }

                    Log.Info("Attaching eye tracking device status changed listener to the Tobii service.");

                    EyeXHost.EyeTrackingDeviceStatusChanged += (s, e) => Log.DebugFormat("Tobii EyeX tracking device status changed to {0}", e);

                    if (Settings.Default.TobiiEyeXProcessingLevel == DataStreamProcessingLevels.None ||
                       Settings.Default.TobiiEyeXProcessingLevel == DataStreamProcessingLevels.Low)
                    {
                        gazeDataStream = EyeXHost.CreateGazePointDataStream(
                            Settings.Default.TobiiEyeXProcessingLevel == DataStreamProcessingLevels.None
                                ? GazePointDataMode.Unfiltered //None
                                : GazePointDataMode.LightlyFiltered); //Low

                        EyeXHost.Start(); // Start the EyeX host

                        gazeDataStream.Next += (s, data) =>
                        {
                            if (pointEvent != null &&
                                !double.IsNaN(data.X) &&
                                !double.IsNaN(data.Y))
                            {
                                pointEvent(this, new Timestamped<Point>(new Point(data.X, data.Y),
                                    new DateTimeOffset(DateTime.UtcNow).ToUniversalTime())); //EyeX does not publish a useable timestamp
                            }
                        };
                    }
                    else
                    {
                        fixationDataStream = EyeXHost.CreateFixationDataStream(
                            Settings.Default.TobiiEyeXProcessingLevel == DataStreamProcessingLevels.Medium
                                ? FixationDataMode.Sensitive //Medium
                                : FixationDataMode.Slow); //Hight

                        EyeXHost.Start(); // Start the EyeX host

                        fixationDataStream.Next += (s, data) =>
                        {
                            if (pointEvent != null &&
                                !double.IsNaN(data.X) &&
                                !double.IsNaN(data.Y))
                            {
                                pointEvent(this, new Timestamped<Point>(new Point(data.X, data.Y),
                                    new DateTimeOffset(DateTime.UtcNow).ToUniversalTime())); //EyeX does not publish a useable timestamp
                            }
                        };
                    }
                }

                pointEvent += value;
            }
```

**Comment by Ar2rZ** [comment]
ok, thanks, will try later this evening.

**Comment by JuliusSweetland** [comment]
Ok. The difference is just the filtering of the NaN values out as they aren't useful.

**Comment by JuliusSweetland** [comment]
I've checked in this fix (on EyeX and TET) to master so if you update from master you can test and let me know if it helps?

**Comment by Ar2rZ** [comment]
looks good, just did a try.

**Comment by JuliusSweetland** [comment]
Great. I'll close this issue and include the fix in the next release. Thanks Arthur.
