### ISSUE TITLE
Ability to input more than one language at a time/switch between languages for input

### ISSUE THREAD

**Issue by JuliusSweetland** [JuliusSweetland/OptiKey#167]
* In order to retain the simulation of physical key presses (e.g. to allow the user to enter shortcuts) I think the virtual key code should be stored on the Key's KeyValue and passed through to the KeyboardOutputService for processing.

* Switching between language keyboards is non-trivial as the simulated key strokes are dependent on the current OS language. Potentially I could drop support for all virtual key codes and just output plain text. This would avoid issues with the OS language being different from the OptiKey language. Alternatively add a new setting to enable/disable virtual key codes and only specify them on the main ALPHA keyboard keys (and number keys on the NUMERIC&SYMBOLS keyboard).

* Add a LATIN keyboard available from the Menu (with no virtual key codes).

* Need to customise the ALPHA keyboard icon to the current language, as "ABC" is not relevent for all character sets and is more suited to an "English" keyboard.

**Comment by Ar2rZ** [comment]
as per my dual(triple) language user experience it will be good to have some thing like choosing  the keyboard layouts (in settings for example) which can be switched between layouts from main keyboard or from menu. for non-latin language layouts will not require to support shortcuts. 
just the opinion.

**Comment by JuliusSweetland** [comment]
This issue ties closely with https://github.com/JuliusSweetland/OptiKey/issues/168 - closing this issue and extending issue #168
