### ISSUE TITLE
Settings

### ISSUE THREAD

**Issue by JuliusSweetland** [JuliusSweetland/OptiKey#18]
* Make them accessible from within ETTA, e.g. new keyboards to change settings
* Edit personalised version of the dictionary:
* Remove entry (including phrases)
* Reset use count on words (individual entry/all entries)

**Comment by alexandre-mbm** [comment]
The milestone Alpha will be the OptiKey **v3**?

**Comment by JuliusSweetland** [comment]
@alexandre-mbm This has been implemented and the issue closed. "v3" is a branch where I was experimenting with 2 floating windows; one containing the keyboard, and the other down the side of the screen for mouse actions.

**Comment by alexandre-mbm** [comment]
What do you say about this approach experienced?

**Comment by JuliusSweetland** [comment]
I don't understand the question I'm afraid...

**Comment by alexandre-mbm** [comment]
Before the OptiKey, I had imagined a mouse panel hidden in lateral of the screen, and a keyboard panel also hidden, it in bottom of the screen. Each them would be showed when the user was looking at its respective corner.

> I don't understand the question I'm afraid...

What you learned with the v3 branch?

**Comment by JuliusSweetland** [comment]
@alexandre-mbm That's how I imagined it. If you'd like to work on that some of the solution is already written on the v3 branch, but it needs to be brought up to date.

**Comment by alexandre-mbm** [comment]
> but it needs to be brought up to date.

 in which aspects?

**Comment by JuliusSweetland** [comment]
It needs the latest master branch merged into the v3 branch, which might
not be straightforward. If you decide to work on this I can help with that
merge.

**Comment by alexandre-mbm** [comment]
Before, we will try use OptiKey out the box, just with a switch for the mouse click. Prevent the visual dwell on mouse pointer will make possible my father use your software as it is already.

**Thank very much. Great work! Sorry.** I will not continues with the conversations. I stopped this. **Here just to thank. Bye.**

**Comment by JuliusSweetland** [comment]
@alexandre-mbm No problem. You're welcome. I hope it works well for you. Email me if you need anything; optikeyfeedback@gmail.com
