### ISSUE TITLE
Blink trigger

### ISSUE THREAD

**Issue by JuliusSweetland** [JuliusSweetland/OptiKey#22]

**Comment by JuliusSweetland** [comment]
Single eye blink could also be used, but this could also be used with mouse actions for left/right clicks? Just an idea.

**Comment by JuliusSweetland** [comment]
Adding to BACKLOG

**Comment by alexandre-mbm** [comment]
- [ ] I need to test if the blink triggers from Project IRIS could be workaround for the lacks of feature on OptiKey.

My father is a ALS person. We will go Tobii EyeX as main input hardware. I think that the OptiKey could manage bindings for keystrokes. I want to use IRIS or to program blink triggers by using the EyeX SDK. I also want to use accelerometers and pressure sensors to implement auxiliary switches with Arduino via USB or bluetooth. So I need to study how to integrate my DIY hardware with OptiKey. I like the idea to work with keystrokes (keycodes), HID interfaces.

@JuliusSweetland, what the OptiKey can offer to me? I still have no time to study its code.

**Comment by JuliusSweetland** [comment]
@alexandre-mbm OptiKey can accept keystrokes (either from a keyboard, or another device which can simulate a keystroke) as triggers to make selections. This particular issue was closed as I have read a reasonable amount of comments that suggest that blinking as a trigger is not reliable enough.

**Comment by alexandre-mbm** [comment]
Yes, blinking as a trigger presents very false positives. But it can be useful in some ways and contexts.

I have experienced binding keystrokes. But is there two action only, is not? I would want to have trigger to customized screens, for example.

By the way, are there customized screens on OptiKey?! Some functions in general will be useless for my father, such as diacritcs. I would want to put them in more distant screens and turn the full utilization of keyboard and mouse (mainly) more near in quantity of actions (clicks).

**Comment by JuliusSweetland** [comment]
There is currently only one type of selection, but it would be possible to
add more, although this is a complex change.

The idea of customised keyboards should be coming in the next few months.
Someone is working on this already!

**Comment by alexandre-mbm** [comment]
> There is currently only one type of selection, but it would be possible to add more, although this is a complex change.
It could starting by doing use of config files. YAML.

Honestly, it's pretty bad use the GUI for configuration (Alt+M). A approach to edit texts files would be applicable, because disabled people are usually aided in thoses steps. Or is there a shortcut to suspend the eye tracker for the person that is configuring the OptiKey?

Having screens is better than having files. But having files can represent economy of development effort. Documentation?

> The idea of customised keyboards should be coming in the next few months. Someone is working on this already!
Who? At GitHub?
