### ISSUE TITLE
BCI (brain computer interface) trigger

### ISSUE THREAD

**Issue by JuliusSweetland** [JuliusSweetland/OptiKey#27]
Off the shelf or research product?

Could approach universities to open this up to students? 

From "gaze interaction and applications of eye tracking"; EEG has around 500ms latency.

**Comment by JuliusSweetland** [comment]
http://neurosky.com/ $80

**Comment by JuliusSweetland** [comment]
Lucas Steuber suggested that MND/ALS affects the electrical patterns that can be detected on the surface of the skin, so this may be a dead end.

**Comment by JuliusSweetland** [comment]
Adding as a misc idea to https://github.com/JuliusSweetland/OptiKey/issues/57

**Comment by alexandre-mbm** [comment]
> Adding to BACKLOG

@JuliusSweetland, do you use some kanban board? Where?
