### ISSUE TITLE
Solve how the selection progress is displayed

### ISSUE THREAD

**Issue by JuliusSweetland** [JuliusSweetland/OptiKey#31]
1. http://www.devcomponents.com/kb2/?p=1117
   ![image](https://cloud.githubusercontent.com/assets/4722561/3635921/f125d202-0f92-11e4-971f-f0f51d2fd85e.png)
2. http://timokorinth.de/creating-circular-progress-bar-wpf-silverlight/
   ![image](https://cloud.githubusercontent.com/assets/4722561/3635922/fc15a9ee-0f92-11e4-9ff9-7ec859480a10.png)
3. http://www.scottlogic.com/blog/2011/02/07/a-circular-progressbar-style-using-an-attached-viewmodel.html
   ![image](https://cloud.githubusercontent.com/assets/4722561/3635930/43aa1ac4-0f93-11e4-9453-2de568fc3c56.png)
   WPF sample project here; http://agsmith.wordpress.com/2008/04/07/propertydescriptor-addvaluechanged-alternative/

**Comment by alexandre-mbm** [comment]
The current approach for the mouse pointer is bad. The dwell at side of it gets the user's attention and then the pointer is moved (provoking imprecision and difficulting the use). I suggest something more "centered" in the "point" of interest.

This is the main reason that is motivating me to look back to switches (accelerometers, pressure sensors, infrared), even knowing that my father can lose fully the capacity of trigger them.

**Comment by JuliusSweetland** [comment]
@alexandre-mbm I agree. The problem is if the selection is at the edge or corner of the screen. You would have to animate a progress indicator that is partially off the screen.

**Comment by alexandre-mbm** [comment]
Do you already tryout an approach with small circle of fire like that found in the EyeX calibration process? The more the person looks, the faster it spins and the more attention it requires. I think that some time configurations could warranty the liberation of our gaze as well as the adjust for the initial approximation do not grab prematurely.

**Comment by JuliusSweetland** [comment]
@alexandre-mbm I haven't implemented other animations, but it would be relatively easy to experiment with ideas.
