### ISSUE TITLE
Enhance selection progress indication by shrinking text/symbol during selection

### ISSUE THREAD

**Issue by JuliusSweetland** [JuliusSweetland/OptiKey#41]
'Gaze interaction and applications of eye tracking' p.221
This technique draws in the user's attention to the centre of the key

**Comment by JuliusSweetland** [comment]
Closing - instead there is a shrinking animation available now, which means the key text/symbol does not have to shrink, which could potentially make broken/resumed selections difficult (as the user may no longer be able to see the key label clearly).

**Comment by alexandre-mbm** [comment]
> 'Gaze interaction and applications of eye tracking' p.221

[Google Books](https://books.google.com.br/books?id=HuWeBQAAQBAJ&hl=pt-BR)
