### ISSUE TITLE
Improve accuracy of multi key selection, especially when using mouse

### ISSUE THREAD

**Issue by JuliusSweetland** [JuliusSweetland/OptiKey#42]
Detect vector changes (changes in direction) and use those to create "anchor" letters to improve the matching to dictionary words.

**Comment by alexandre-mbm** [comment]
@JuliusSweetland, can you speak a few about the autocomplete's intelligence?

**Comment by JuliusSweetland** [comment]
@alexandre-mbm At the moment the multi-key selection registers all individual points coming from the tracker and counts how many are within the boundaries of each key. I apply a band pass filter to remove keys which have not received significant attention. I then have a list, in order, of keys which the user is interested in and I match that to the dictionary entries using the lowest common subs-equence algorithm. It works better than I expected so I've got no desire to complicate this at the moment.
