### ISSUE TITLE
Look into low cost Windows tablets for a complete system with EyeTribe

### ISSUE THREAD

**Issue by JuliusSweetland** [JuliusSweetland/OptiKey#44]
http://www.microsoftstore.com/store/msuk/en_GB/pdp/HP-Stream-7-Signature-Edition-Tablet/productID.308686300?tid=sMfzoUBir_dc&cid=5366&pcrid=50345397525&pkw=%2Bmicrosoft%20%2Bhp%20%2B7%20%2Binch%20%2Btablet&pmt=b&WT.srch=1&WT.mc_id=pointitsem_Microsoft+UK_google_HP+Stream+Tablet&WT.term=%2Bmicrosoft%20%2Bhp%20%2B7%20%2Binch%20%2Btablet&WT.campaign=HP+Stream+Tablet&WT.content=MfzoUBir&WT.source=google&WT.medium=cpc

**Comment by alexandre-mbm** [comment]
OptiKey /docs / [**Low cost tablets and laptops.txt**](https://github.com/OptiKey/OptiKey/blob/master/docs/Low%20cost%20tablets%20and%20laptops.txt)

**Comment by JuliusSweetland** [comment]
@alexandre-mbm A new keyboard specifically customised for internet browsing could work.

**Comment by alexandre-mbm** [comment]
I am seeing #152 and some day I will put attention on v3 branch.
