### ISSUE TITLE
Some screenshots

### ISSUE THREAD

**Issue by JuliusSweetland** [JuliusSweetland/OptiKey#47]
![image](https://cloud.githubusercontent.com/assets/4722561/5583701/2821eada-9075-11e4-955e-55f64e0f2c11.png)

![image](https://cloud.githubusercontent.com/assets/4722561/5583703/32a16012-9075-11e4-8257-5b527c27b598.png)

![image](https://cloud.githubusercontent.com/assets/4722561/5583707/3d9eb686-9075-11e4-8576-64414df4e796.png)

![image](https://cloud.githubusercontent.com/assets/4722561/5583712/4e2150d6-9075-11e4-8f6e-7eef2c09b7b9.png)

![image](https://cloud.githubusercontent.com/assets/4722561/5583717/59771bb4-9075-11e4-9b8c-5568913b90d3.png)

![image](https://cloud.githubusercontent.com/assets/4722561/5583719/63b4f4ac-9075-11e4-8ff0-20ecdd93b5b1.png)

![image](https://cloud.githubusercontent.com/assets/4722561/5583720/6e35c1fe-9075-11e4-924b-57061b2628ef.png)

![image](https://cloud.githubusercontent.com/assets/4722561/5583724/76b15c62-9075-11e4-9421-a5b5703e806e.png)

![image](https://cloud.githubusercontent.com/assets/4722561/5583725/7ec49216-9075-11e4-891a-466f160c1729.png)

![image](https://cloud.githubusercontent.com/assets/4722561/5583729/89c97762-9075-11e4-9e3c-5be8118e5a78.png)

![image](https://cloud.githubusercontent.com/assets/4722561/5583732/93266202-9075-11e4-812d-56c2ca469b9d.png)

![image](https://cloud.githubusercontent.com/assets/4722561/5583740/a8e14ed6-9075-11e4-85d9-f556293df1a1.png)

**Comment by JuliusSweetland** [comment]
![image](https://cloud.githubusercontent.com/assets/4722561/5808262/7af6e860-a023-11e4-82f5-4ab5c77afe59.png)

![image](https://cloud.githubusercontent.com/assets/4722561/5808296/dd090a74-a023-11e4-8495-aa8dda47564c.png)

**Comment by JuliusSweetland** [comment]
![image](https://cloud.githubusercontent.com/assets/4722561/6257202/53bac438-b7b6-11e4-8f5f-58c66f6bde06.png)
![image](https://cloud.githubusercontent.com/assets/4722561/6257208/5f3937a4-b7b6-11e4-95fb-565c11f2ecf7.png)
![image](https://cloud.githubusercontent.com/assets/4722561/6257223/6d37b3da-b7b6-11e4-9c42-f2ab509dd957.png)
![image](https://cloud.githubusercontent.com/assets/4722561/6257228/7543c7ee-b7b6-11e4-9830-9cccbc885974.png)

**Comment by JuliusSweetland** [comment]
![image](https://cloud.githubusercontent.com/assets/4722561/6276757/f7a2dea8-b880-11e4-82c0-c5b72191d42f.png)
![image](https://cloud.githubusercontent.com/assets/4722561/6276762/fb2bbcc0-b880-11e4-8d8e-f777e91b0216.png)
![image](https://cloud.githubusercontent.com/assets/4722561/6276764/ffbafc92-b880-11e4-8905-0e1651a008e6.png)

**Comment by alexandre-mbm** [comment]
Old version? Here the labels are showed when focus in the icons.

**Comment by JuliusSweetland** [comment]
@alexandre-mbm Correct. All closed issues have been implemented or ignored for some reason. You can ignore the "in progress" label if the issue is closed.
