### ISSUE TITLE
Sort out sizing/layout of suggestions

### ISSUE THREAD

**Issue by JuliusSweetland** [JuliusSweetland/OptiKey#53]
Phrases should wrap

Individually size? OR Size consistently, but wrap letters (breaking words) so as large as possible

**Comment by JuliusSweetland** [comment]
I don't think this is a big deal. Closing.

**Comment by alexandre-mbm** [comment]
How it is today? Truncated?
And are there phrases as suggestions?!

If they becomes truncated, you could use a tooltip while doing the dwell...
