### ISSUE TITLE
Clarify settings by adding previews, prompts, etc

### ISSUE THREAD

**Issue by JuliusSweetland** [JuliusSweetland/OptiKey#54]
Rename point source settings to mouse click or something similar

Preview images/render of settings?

Add help prompts in management console

**Comment by JuliusSweetland** [comment]
Moving to BACKLOG

**Comment by alexandre-mbm** [comment]
Is possible manage configurations by editing files directly? What I read or study to learn it?

**Comment by JuliusSweetland** [comment]
@alexandre-mbm The settings are stored in xml files, with the syntax is not user friendly, you can easily "break" the file with a bad edit, and the directory is deliberately kept away from the user (by Microsoft).

**Comment by alexandre-mbm** [comment]
Okay, I understand. It serves at least to backup and restore, manual or automatic. Thanks!

![appdata-user](https://cloud.githubusercontent.com/assets/957501/20333414/29838e04-ab91-11e6-8d43-63975f10aa1c.png)

![appdata-more](https://cloud.githubusercontent.com/assets/957501/20333419/33a6644c-ab91-11e6-8d94-b84dbad47d65.png)
