### ISSUE TITLE
Make toast notifications themable

### ISSUE THREAD

**Issue by JuliusSweetland** [JuliusSweetland/OptiKey#55]

**Comment by alexandre-mbm** [comment]
I did not understand what this means. Can you give me a example?

**Comment by JuliusSweetland** [comment]
@alexandre-mbm You can ignore any closed issues. They may still also be labelled as "in progress" incorrectly, but the fact that they are closed means they issue has been fixed, or discarded for whatever reason.

**Comment by alexandre-mbm** [comment]
Sorry me if my mode is bad. I would want to know the details of your options in the OptiKey history. I am reading all issues (open and closed). If it bothers you, declare to me please. So I will stop.

I also will study the code, after. I think that the Github's issues are an optimal tool for knowledge management. To generate it and to record it from initial times.

On the other hand, I want congratulate you for this excellent documentation that is the wiki. It were a good idea doing the domain pointing to it.

**Comment by JuliusSweetland** [comment]
I'm very happy for you to read the issues - good idea. Just don't worry too
much about the closed issues as there are plenty of open issues to solve
first!
