### ISSUE TITLE
Investigate horizontal screen splitter applications for use alongside OptiKey

### ISSUE THREAD

**Issue by JuliusSweetland** [JuliusSweetland/OptiKey#62]
* MaxTo - $17 – can define regions and Ctrl+Win+Up/Down for horizontal splitting - https://maxto.net/using

* WindowSpace - http://www.ntwind.com/software/windowspace.html

* AutoHotKey + script - http://www.pixelchef.net/how-snap-windows-horizontally-windows-7

**Comment by alexandre-mbm** [comment]
@JuliusSweetland, did you decided to implement the interesting into OptiKey?
If not, can you comment the evaluation of this three tools?

WindowSpace costs $24.

**Comment by JuliusSweetland** [comment]
@alexandre-mbm I instead added support for docking, which achieves a similar thing by arranging other windows around OptiKey.
