### ISSUE TITLE
Add support for more languages / improve word lists

### ISSUE THREAD

**Issue by JuliusSweetland** [JuliusSweetland/OptiKey#68]
Word lists: https://invokeit.wordpress.com/frequency-word-lists/ from credits on http://www.gazespeaker.org/credits/ (which also contains links to Japanese word lists)

**Comment by JuliusSweetland** [comment]
Current English word lists were generated here: http://app.aspell.net/create?defaults=en_GB-ise

**Comment by alexandre-mbm** [comment]
From README.md at SCOWL's Github repository:
> SCOWL is derived from many sources under a BSD compatible license. The combined work is freely available under a **MIT**-like license.
