### ISSUE TITLE
Add support for gamepads (so joystick/gamepad buttons can be used for selection)

### ISSUE THREAD

**Issue by JuliusSweetland** [JuliusSweetland/OptiKey#70]
http://stackoverflow.com/questions/3929764/taking-input-from-a-joystick-with-c-sharp-net
http://stackoverflow.com/questions/12619385/slimdx-joystick-poll-succeeds-on-disconnected-gamepad/12988935#12988935

**Comment by alexandre-mbm** [comment]
Doing a central of binding for keystrokes, with profiles that would be enabled or disabled for certain contexts, could solve this and my issues with flexibility. Gamepads and others switch sources can be mapped by third party to virtual keystrokes. OptiKey just need manage keystrokes by doing the binding of each them to its internal actions.

**Comment by JuliusSweetland** [comment]
@alexandre-mbm I agree, physical keypads which simulate keystrokes can interfere with OptiKey also simulating keystrokes as they can combine. Joysticks generate a separate stream of inputs which do not overlap with keystrokes, so there is some advantage in adding support for them.
