### ISSUE TITLE
Featured in biggest dutch tech community 

### ISSUE THREAD

**Issue by NinoFloris** [JuliusSweetland/OptiKey#76]
https://translate.google.nl/translate?sl=auto&tl=en&js=y&prev=_t&hl=en&ie=UTF-8&u=http%3A%2F%2Ftweakers.net%2Fnieuws%2F105215%2Fontwikkelaar-brengt-opensourcesoftware-voor-als-patienten-uit.html&edit-text=
Or original link
http://tweakers.net/nieuws/105215/ontwikkelaar-brengt-opensourcesoftware-voor-als-patienten-uit.html

I and they admire your work, thank you.

P.S.
This was a suggestion by one of the commenters, you should check out the word prediction engine they use (this is the software built in collaboration with Stephen Hawking):
https://github.com/01org/acat

**Comment by JuliusSweetland** [comment]
Thank you - that's immense!

The word prediction engine is separate from ACAT and called Presage. It's on my (massive) todo list.
