### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by wanderer** [JuliusSweetland/OptiKey#77]
it would be nice. would mono work?

**Comment by whackashoe** [comment]
I know it uses WPF so the GUI would need to be ported.

**Comment by sabas** [comment]
In VS2015 you can target Linux+Mac if using dotnet core (I couldn't find how however).
I just found this talk https://channel9.msdn.com/Events/Build/2015/3-670

**Comment by JuliusSweetland** [comment]
Yeah WPF is the problem here.

**Comment by whackashoe** [comment]
I think qt might be easiest for crossplatform. 

@JuliusSweetland I took a short look but not familiar w/ the code at all - is that all that is needed to be ported? I saw a few dlls packaged with, are those all os?

**Comment by whackashoe** [comment]
Also - testing on wine-1.7.50 using windows 8.1, install goes well. But running software itself gives me this output: [https://killr.io/ajcgf](https://killr.io/ajcgf)

**Comment by JuliusSweetland** [comment]
Thank you for trying, but I'm not surprised OptiKey doesn't play nicely with Wine.

**Comment by JuliusSweetland** [comment]
Closing this issue as I have created a more general "Cross-platform" issue #105
