### ISSUE TITLE
Add support for OSX

### ISSUE THREAD

**Issue by quantumpotato** [JuliusSweetland/OptiKey#78]
What would this take? I would throw in $500 if it worked well to look to direct the mouse then tap a button on my keyboard to click.

**Comment by JuliusSweetland** [comment]
If you can find an eye tracker that plays nicely with Parallels then this may already be possible as OptiKey runs in Parallels (within a Windows virtual machine)

**Comment by ramshorst** [comment]
Native OSX support would be awesome!

**Comment by JuliusSweetland** [comment]
Closing this issue as I have created a more general "Cross-platform" issue #105
