### ISSUE TITLE
Show selection progress and complete selections

### ISSUE THREAD

**Issue by JuliusSweetland** [JuliusSweetland/OptiKey#8]
- Display selection progress on keys if in SelectionMode == Key
- Display selection (complete) on key if SelectionMode == Key
- Stub out showing selection progress on cursor if SelectionMode == Point
- Stub out showing selection (complete) on cursor if SelectionMode == Point

**Comment by alexandre-mbm** [comment]
selection progress == dwell ?

**Comment by JuliusSweetland** [comment]
@alexandre-mbm Selection doesn't have to be dwell, but at the moment, selection progress only applies to the dwell trigger.

**Comment by alexandre-mbm** [comment]
I was naming as "dwell" the animation, but I see that are three types* of animation now:

![dwell-and-its-types](https://cloud.githubusercontent.com/assets/957501/20331894/23ac7770-ab87-11e6-9b9e-ea3047dd5749.png)

At the Transifex I find that term by meaning "fixation" (for my language, portuguese).

\* It is good to know that will be sufficient adding others behaviours of indicator, to improve a lot the pointer precision.
