### ISSUE TITLE
Debugging display

### ISSUE THREAD

**Issue by JuliusSweetland** [JuliusSweetland/OptiKey#9]
- Debug setting
- Display points from SelectionResult event - if Debug == true
- Display points per second (in CaptureState frame?) if Debug == true

**Comment by alexandre-mbm** [comment]
Is there how to activate the debug without rebuild?

**Comment by JuliusSweetland** [comment]
This has been implemented. There is a setting in the Management Console (in the "Other" tab) to turn on/off debug mode. When on you see the points selected by the user, points per seconds coming from the points source (e.g. the eye tracker), and the logs include a LOT more detail.
